- hosts: master
  become: yes
  tasks:
    - name: append to cron file
      command: echo "0 22 * * FRI /home/cuadmin/ubiquitous-octo-umbrella/cron-start.sh"

    - name: restart crond service
      command: systemctl restart crond.service
